apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
  namespace: kube-learning
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /data/flask-app-shared-pv
    type: Directory
