apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pv
  namespace: kube-learning
spec:
  resources:
    requests:
      storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
